"""add base attack and defense to hero classes

Revision ID: 1fe145aaaa18
Revises: e96c734a9046
Create Date: 2026-06-01 23:56:51.436306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe145aaaa18'
down_revision: Union[str, Sequence[str], None] = 'e96c734a9046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero_classes', sa.Column('base_attack', sa.Integer(), nullable=False))
    op.add_column('hero_classes', sa.Column('base_defense', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero_classes', 'base_defense')
    op.drop_column('hero_classes', 'base_attack')
    # ### end Alembic commands ###
