"""add defaults to base_attack and base_defense, remove defaults from hero attack and defense

Revision ID: e938c6191d81
Revises: 1fe145aaaa18
Create Date: 2026-06-02 00:04:31.867362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e938c6191d81'
down_revision: Union[str, Sequence[str], None] = '1fe145aaaa18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
