"""add attack and defense fields to heroes

Revision ID: e96c734a9046
Revises: a1d17b611cbf
Create Date: 2026-06-01 23:48:27.669090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96c734a9046'
down_revision: Union[str, Sequence[str], None] = 'a1d17b611cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('attack', sa.Integer(), nullable=False))
    op.add_column('heroes', sa.Column('defense', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'defense')
    op.drop_column('heroes', 'attack')
    # ### end Alembic commands ###
